# Generated by Django 6.1.1 on 2026-09-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('applied', 'Beworben'), ('interview', 'Gespräch'), ('rejected', 'Absage'), ('offer', 'Zusage')], default='applied', max_length=20)),
                ('follow_up', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
