# Generated by Django 6.1.1 on 2026-09-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='address',
        ),
        migrations.AddField(
            model_name='application',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
