# Generated by Django 6.1.1 on 2026-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_address_application_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='channel',
            field=models.CharField(blank=True, choices=[('email', 'E-Mail'), ('portal', 'Portal'), ('post', 'Post'), ('phone', 'Telefon'), ('personal', 'Persönlich')], max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='response_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='work_mode',
            field=models.CharField(blank=True, choices=[('onsite', 'Vor Ort'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20),
        ),
    ]
