# Generated by Django 6.1.1 on 2026-10-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_application_channel_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('planned', 'Geplant'), ('unsure', 'Unsicher'), ('applied', 'Beworben'), ('interview', 'Gespräch'), ('rejected', 'Absage'), ('offer', 'Zusage')], default='applied', max_length=20),
        ),
    ]
