# Generated by Django 6.1.1 on 2026-10-04 15:05

import application.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_application_is_favorite_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=application.models.upload_path)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(choices=[('cover_letter', 'Anschreiben'), ('cv', 'Lebenslauf'), ('certificate', 'Zeugnis'), ('other', 'Sonstiges')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='application.application')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
